### ISSUE TITLE
react should be a peer-dependency

### ISSUE THREAD

**Issue by hverlin** [vscode-elements/react-elements#4]
React should be a peer dependency otherwise two versions of react might get loaded: https://github.com/vscode-elements/react-elements/blob/acdfc5b5a78f59d32b86da802775966b16ad997e/packages/lib/package.json#L29

As a workaround, one might can override the version of react used. Example with `pnpm`:
```json
	"pnpm": {
		"overrides": {
			"react": "18.3.1"
		}
	}
```

**Comment by bendera** [comment]
Indeed, I agree with you. I'm a bit puzzled about what version range I should use. `"17.x || 18.x"` or `"~17.0 || ~18.0"`? Please advise. Or even open a PR.

**Comment by hverlin** [comment]
I think you can just indicate`^18.0.0` until someone requests a different version

**Comment by bendera** [comment]
Done.
